# Generated by Django 6.0 on 2026-01-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('can_modify_tags', 'Can add/remove tags on photos')]},
        ),
    ]
